development: 
  cloud_name: "jairo-coder-academy"
  api_key: "327426852913276"
  api_secret: "NFsjzozo08dNxD-e859QqSrTLKo"
  secure: true

production:
  cloud_name: "jairo-coder-academy"
  api_key: "327426852913276"
  api_secret: "NFsjzozo08dNxD-e859QqSrTLKo"
  secure: true